fraud_analytics:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: "{{ env_var('CLICKHOUSE_HOST', 'localhost') }}"
      port: "{{ env_var('CLICKHOUSE_PORT', '8123') | int }}"
      user: "{{ env_var('CLICKHOUSE_USER', 'default') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD', 'clickhouse') }}"
      schema: fraud
      secure: false
      verify: false
      connect_timeout: 10
      send_receive_timeout: 300

    prod:
      type: clickhouse
      host: "{{ env_var('CLICKHOUSE_HOST', 'clickhouse') }}"
      port: "{{ env_var('CLICKHOUSE_PORT', '8123') | int }}"
      user: "{{ env_var('CLICKHOUSE_USER', 'default') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD', 'clickhouse') }}"
      schema: fraud
      secure: false
      verify: false
      connect_timeout: 10
      send_receive_timeout: 600
