apiVersion: v1
kind: Namespace
metadata:
  name: fraud-detection
  labels:
    app.kubernetes.io/part-of: fraud-detection-platform
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/part-of: fraud-detection-platform
    purpose: observability
