apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"
      httpMethod: POST

  - name: Jaeger
    type: jaeger
    access: proxy
    orgId: 1
    url: http://jaeger-query.monitoring.svc:16686
    editable: false
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags: ["service.name"]
